<?php
	$TextDB = array
	(
		"en" => array(
						"LANG_NAME"   		=> "English",
						"login_button" 		=> "Log In", 
						"auth_title" 		=> "Authorization",
						
						"main_statistics" 	=> "Statistics",
						"main_total_data" 	=> "Total Data",
						"main_total_http" 	=> "Total HTTP/HTTPS",
						"main_total_ftp" 	=> "Total FTP/SFTP/SSH",
						"main_total_wallet" => "Total Wallets",
						"main_total_other" 	=> "Total Others",
						"main_total_report" => "Total Reports",
						"main_top_bin_id_bots" => "Top Bin IDs (Bots)",
						"main_top_bin_id_report" => "Top Bin IDs (Reports)",
						"main_table_screen" => "Screenshot",
						"main_new_report_1" => "New Reports in the last hour",
						"main_new_report_24"=> "New Reports in the last 24 hours",
						"main_total_bots" => "Total Bots",
						"main_total_errors" => "Total errors",
						"main_new_botsnew_1" => "Total new Bots in the last hour",
						"main_new_botsnew_24"=> "Total new Bots in the last 24 hours",
						"main_new_botsnew_7"=> "Total new Bots in the last 7 days",
						"main_new_bots_1" => "Total online Bots in the last hour",
						"main_new_bots_24"=> "Total online Bots in the last 24 hours",
						"main_new_bots_7"=> "Total online Bots in the last 7 days",
						"main_top_client" 	=> "Top Client List",
						"main_top_wallet" 	=> "Top Wallet client List",
						"main_top_country" 	=> "Top Country List (Reports)",
						"main_top_country_bot" 	=> "Top Country List (Bots)",
						"main_php_version" 	=> "PHP Version",
						"main_server_information" 	=> "Server Information",
						"main_last_data" 	=> "Last Data",
						
						"report_view_set_command" 	=> "Command",
						"report_view_last_online" => "Last Online",
						"main_last_wallet" 	=> "Last Wallet",
						"http_export_all" 	=> "Export All",
						"http_export_selected" 	=> "Export Selected Items",
						"http_delete_all" 	=> "Delete All",
						"http_delete_selected" 	=> "Delete Selected Items",
						"http_table_data" 	=> "Data",
						"http_table_client" => "Application",
						"http_table_report" => "Report",
						"http_table_time" 	=> "Date",
						"http_page_back" 	=> "Previous",
						"http_page_next" 	=> "Next",
						"maint_total_dumps" 	=> "Total Dumps",
						"report_table_ip"   => "IP Address",
						
						"reportv_table_data"=> "Report Data",
						"reportv_table_guid"=> "GUID",
						"reportv_table_os" 	=> "OS",
						"reportv_table_country"=> "Country",
						"reportv_table_arc" => "Architecture",
						"reportv_table_acc" => "Account Type",
						"reportv_table_elev"=> "Elevated",
						"reportv_table_hash"=> "Report hash",
						"reportv_table_wallet"=> "Wallets",
						
						"report_exportpw" => "Export Password",
						"report_export_all" 	=> "Export Report",
						"report_export_all_mark" 	=> "Export Report (Client name)",
						"report_export_delete" 	=> "Delete Report",
						
						"chart_reports" => "Reports",
						"chart_ftp" 	=> "FTP",
						"chart_dump" 	=> "DUMP",
						"chart_http" 	=> "HTTP",
						"chart_data" 	=> "OTHER",
						"chart_wallet" 	=> "WALLET",
						"chart_count" 	=> "Count",
						"chart_hours" 	=> "Hours",
						"chart_new_pass"=> "New data additions in the past 24 hours",
						"chart_oss" 	=> "Operation System Statistics (Reports)",
						"chart_oss_bots" 	=> "Operation System Statistics (Bots)",
						"chart_osd" 	=> "Operating Systems Data",
						"chart_architecture" => "Architecture",
						"chart_account" 	=> "Account",
						"chart_privileges" 	=> "Privileges",
						"chart_32bit" 		=> "32-bit",
						"chart_64bit" 		=> "64-bit",
						"chart_admin" 	=> "admin",
						"table_bot_name" 	=> "Name",
						"chart_user" 	=> "user",
						"chart_nonelevated" 	=> "simple",
						"chart_elevated" 	=> "elevated",
						"chart_aos" 	=> "Additional OS statistics",
						"wallet_balance" 	=> "Balance",
						"wallet_locked" 	=> "Locked",
						"wallet_size" 	=> "Size",
						"wallet_transaction" 	=> "Transaction",
						// Showing 0 to 4 of 4 entries. 
						"table_show" 	=> "Showing",
						"table_to" 		=> "to",
						"table_of" 		=> "of",
						"table_entries" => "entries",
						
						"settings_user"	=> "User Settings",
						"settings_admin"=> "Admin Settings",	
						"settings_logs" => "Logs",
						
						"settings_change" 		=> "Change",
						"settings_set" => "  Set  ",	
						"settings_page_limit" => "Page Limit",
						"settings_languages" => "Languages",
						"settings_set_jid" => "Set JID",
						
						"settings_change_password" 		=> "Password Change",
						"settings_password_dont_match" => "Password don\'t match!",
						"settings_password_too_short" => "Password too short!",							
						"settings_add" => "  Add  ",
						"settings_add_user" => "Add new user",
						"settings_user_list" => "Users lists",
						"settings_server_settings" => "Server settings",
						
						"settings_admin_flush_all" => "Flush all table",
						"settings_remove_allfiles" => "Remove all files",
						"settings_show_phpinfo" => "Show PHP Info",
						
						"settings_admin_new_name" => "User",
						"settings_admin_new_priv" => "Privileges",
						"settings_admin_new_lastview" => "Last View",
						"settings_admin_new_lastlogin" => "Last Login",
						"settings_admin_new_action" => "Action",
						
						"table_all_country" => "All Country",
						"table_all_type" => "All Type",
						"table_all_client" => "All Clients",
						"table_locked" => "Locked",
						"table_not_locked" => "Not Locked",
						"table_transaction" => "Transactions",
						"table_no_transaction" => "No Transactions",
						"table_inpected" => "Checked",
						"table_not_inspected" => "Not Checked",
						"table_show_search" => "Show search",
						"table_search" => "Search",
						
						"table_report_num" => "report",
						"table_report_nums" => "reports",
						
						
						"command_table_addnew" => "Add new command",
						"command_table_comment" => "Comment",
						"command_table_dateurl" => "Data/Url",
						"command_table_type" => "Type",
						"command_table_limit" => "Limit",
						"command_table_timelimit" => "Time limit",
						"command_table_binid" => "Bin ID",
						"command_table_bguid" => "Bot Guid",
						"command_table_elevated" => "Elevated",
						"command_table_coin_related" => "Coin related",
						"command_table_duplicate" => "Duplicate",
						
						"command_table_command" => "Command",
						"command_table_loads" => "Loads",
						"command_table_active" => "Active",
						"command_table_unlimited" => "Unlimited",
						"command_table_commmandlist" => "Commands list",
						"command_table_setcb" => "Set",
						"command_table_delete" => "Delete",
						"command_table_start" => "Start",
						"command_table_stop" => "Stop",
						"command_table_all" => "ALL",
						"command_table_yes" => "YES",
						"command_table_no" => "NO",
						"command_table_pcinfo" => "PC Information",
						"command_table_firston" => "Fist Online",
						"command_table_laston" => "Last Online",
						"main_server_time" => "Server Time",
						
						"report_table_screen" => "Screen size",
					  ),
		"ru" => array(	
						"LANG_NAME"   => "Russian",
						"login_button" 	=> "Log In", 
						"auth_title" 	=> "Authorization"
					  )
	);
	